# Generated by Django 4.1 on 2023-03-21 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbConn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dns', models.URLField(max_length=256, verbose_name='数据库地址')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='表')),
                ('conn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchemaGenerator.dbconn', verbose_name='数据库地址')),
            ],
        ),
    ]
