# Generated by Django 4.1 on 2023-03-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchemaGenerator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbconn',
            name='dns',
            field=models.CharField(max_length=256, verbose_name='数据库地址'),
        ),
    ]
