# Generated by Django 4.1 on 2023-03-21 02:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SchemaGenerator', '0003_dbconn_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='schema',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='schema'),
            preserve_default=False,
        ),
    ]
