# Generated by Django 4.1 on 2023-03-21 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchemaGenerator', '0005_remove_table_schema_dbconn_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='conn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='SchemaGenerator.dbconn', verbose_name='数据库地址'),
        ),
    ]
