# Generated by Django 4.1 on 2023-03-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchemaGenerator', '0007_dbconn_db_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbconn',
            name='db_type',
            field=models.CharField(choices=[('MySQL', 'Mysql'), ('PostgreSQL', 'Postgresql')], default='PostgreSQL', max_length=16, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='dbconn',
            name='dns',
            field=models.CharField(max_length=256, verbose_name='地址'),
        ),
    ]
