# Generated by Django 4.1 on 2023-03-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchemaGenerator', '0011_dbconn_target_schema_dbconn_target_table_name_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbconn',
            name='db_type',
            field=models.CharField(choices=[('MySQL', 'Mysql'), ('PostgreSQL', 'Postgres')], default='PostgreSQL', max_length=16, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='dbconn',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='数据库'),
        ),
        migrations.AlterField(
            model_name='dbconn',
            name='target_table_name_prefix',
            field=models.CharField(blank=True, help_text='可选参数 默认为：数据库 + _', max_length=128, verbose_name='目标表前缀'),
        ),
    ]
